export const BASE_GAMES = [
  // === CARD-HEAVY GAMES ordered by hobbyist/aficionado popularity ===
  {
    id: "dominion",
    name: "Dominion",
    description: "Build your deck by buying action, treasure, and victory cards each turn",
    icon: "👑",
    playerCount: "2-4",
    duration: "30-45 min",
    category: "Cards",
  },
  {
    id: "codenames",
    name: "Codenames",
    description: "Give one-word clues to help your team guess secret agents from a grid of cards",
    icon: "🕵️",
    playerCount: "4-8",
    duration: "15-30 min",
    category: "Cards",
  },
  {
    id: "love-letter",
    name: "Love Letter",
    description: "Deduce, bluff, and outwit with just 16 cards to deliver your letter to the princess",
    icon: "💌",
    playerCount: "2-6",
    duration: "15-20 min",
    category: "Cards",
  },
  {
    id: "sushi-go",
    name: "Sushi Go!",
    description: "Draft the best combination of sushi dishes as cards pass around the table",
    icon: "🍣",
    playerCount: "2-5",
    duration: "15-20 min",
    category: "Cards",
  },
  {
    id: "coup",
    name: "Coup",
    description: "Bluff, steal, and assassinate your way to being the last player standing",
    icon: "🗡️",
    playerCount: "2-6",
    duration: "15 min",
    category: "Cards",
  },
  {
    id: "hanabi",
    name: "Hanabi",
    description: "Cooperatively build fireworks displays — but you can see everyone's hand except your own",
    icon: "🎆",
    playerCount: "2-5",
    duration: "25 min",
    category: "Cards",
  },
  {
    id: "skull",
    name: "Skull",
    description: "Place flowers and skulls face-down, then dare others to flip without hitting a skull",
    icon: "💀🌹",
    playerCount: "3-6",
    duration: "15-30 min",
    category: "Cards",
  },
  {
    id: "six-nimmt",
    name: "6 Nimmt!",
    description: "Play numbered cards simultaneously — avoid being the one to take the 6th card in a row",
    icon: "🐂",
    playerCount: "2-10",
    duration: "20-30 min",
    category: "Cards",
  },
  {
    id: "the-game",
    name: "The Mind",
    description: "Play cards in ascending order without communicating — pure telepathy",
    icon: "🧠",
    playerCount: "2-4",
    duration: "15-20 min",
    category: "Cards",
  },
  {
    id: "exploding-kittens",
    name: "Exploding Kittens",
    description: "Draw cards and try not to explode — use defuses and attacks to survive",
    icon: "🐱💣",
    playerCount: "2-5",
    duration: "15-20 min",
    category: "Cards",
  },
  {
    id: "werewolf",
    name: "One Night Ultimate Werewolf",
    description: "Figure out who the werewolves are before they figure out you know",
    icon: "🐺",
    playerCount: "3-10",
    duration: "10-15 min",
    category: "Cards",
  },
  {
    id: "cards-against-humanity",
    name: "Cards Against Humanity",
    description: "Fill in the blank with the most outrageous answer to win each round",
    icon: "😈",
    playerCount: "4-20",
    duration: "30-90 min",
    category: "Cards",
  },
  {
    id: "unstable-unicorns",
    name: "Unstable Unicorns",
    description: "Build a unicorn army while sabotaging everyone else's stable",
    icon: "🦄",
    playerCount: "2-8",
    duration: "30-45 min",
    category: "Cards",
  },
  {
    id: "uno",
    name: "UNO",
    description: "Match colors and numbers — but watch out for reverses, skips, and Draw 4s!",
    icon: "🔴",
    playerCount: "2-10",
    duration: "15-30 min",
    category: "Cards",
  },
  {
    id: "dobble",
    name: "Dobble / Spot It!",
    description: "Race to find the one matching symbol between any two cards",
    icon: "👁️",
    playerCount: "2-8",
    duration: "10-15 min",
    category: "Cards",
  },
  {
    id: "apples-to-apples",
    name: "Apples to Apples",
    description: "Match nouns to adjectives — the judge picks the funniest or best pairing",
    icon: "🍎",
    playerCount: "4-10",
    duration: "30-75 min",
    category: "Cards",
  },
  {
    id: "bears-vs-babies",
    name: "Bears vs Babies",
    description: "Build monstrous bears to eat horrible babies — from the Exploding Kittens creators",
    icon: "🐻👶",
    playerCount: "2-5",
    duration: "15-20 min",
    category: "Cards",
  },
  {
    id: "taco-cat",
    name: "Taco Cat Goat Cheese Pizza",
    description: "Flip cards and slap the pile when card and word match — fastest hand wins",
    icon: "🌮🐱",
    playerCount: "2-8",
    duration: "10-15 min",
    category: "Cards",
  },
  {
    id: "phase-10",
    name: "Phase 10",
    description: "Complete 10 phases of card combinations — sets, runs, and color groups",
    icon: "🔟",
    playerCount: "2-6",
    duration: "45-90 min",
    category: "Cards",
  },
  {
    id: "skip-bo",
    name: "Skip-Bo",
    description: "Be the first to play through your entire stockpile using sequential builds",
    icon: "⏭️",
    playerCount: "2-6",
    duration: "20-60 min",
    category: "Cards",
  },
  // === BOARD GAMES ordered by hobbyist popularity ===
  {
    id: "risk",
    name: "Risk",
    description: "Command armies and conquer territories across the globe",
    icon: "⚔️",
    playerCount: "2-6",
    duration: "120-360 min",
    category: "Strategy",
  },
  {
    id: "scrabble",
    name: "Scrabble",
    description: "Form words from letter tiles for maximum points",
    icon: "📝",
    playerCount: "2-4",
    duration: "60-90 min",
    category: "Word",
  },
  {
    id: "clue",
    name: "Clue",
    description: "Solve the mystery — who did it, where, and with what weapon?",
    icon: "🔍",
    playerCount: "3-6",
    duration: "45-60 min",
    category: "Mystery",
  },
  {
    id: "monopoly",
    name: "Monopoly",
    description: "Buy, sell, and trade properties to bankrupt your opponents",
    icon: "🏠",
    playerCount: "2-8",
    duration: "60-180 min",
    category: "Strategy",
  },
  {
    id: "trivial-pursuit",
    name: "Trivial Pursuit",
    description: "Test your knowledge across six categories",
    icon: "🧠",
    playerCount: "2-6",
    duration: "60-120 min",
    category: "Trivia",
  },
  {
    id: "game-of-life",
    name: "Game of Life",
    description: "Navigate life's milestones from college to retirement",
    icon: "🎡",
    playerCount: "2-6",
    duration: "60-90 min",
    category: "Family",
  },
] as const;

export type BaseGameId = (typeof BASE_GAMES)[number]["id"];

export const GAME_CATEGORIES = [
  "All",
  "Cards",
  "Strategy",
  "Family",
  "Word",
  "Mystery",
  "Trivia",
] as const;

export const RULE_MUTATIONS: Record<string, string[]> = {
  monopoly: [
    "Free Parking collects all tax money — whoever lands there gets the pot!",
    "If you roll doubles three times, you go to jail AND lose a property of your choice.",
    "Every time someone passes Go, ALL players collect $100.",
    "You can challenge another player to a trivia question to avoid paying rent.",
    "Properties can only be bought at auction — no direct purchases allowed.",
    "Landing on someone's hotel triggers a 'Buyout Battle' — both players roll, highest wins the property.",
    "Every 5th turn is 'Wild Card' turn — draw from a custom event deck.",
    "Players can form temporary alliances that last exactly 3 rounds.",
    "Jail becomes 'Vacation' — you collect double salary but skip 2 turns.",
    "If you go bankrupt, you become a 'Ghost Player' who can still collect Go money and mess with others.",
  ],
  clue: [
    "Each player has a secret 'alibi' card that can be played once to deflect suspicion.",
    "Rooms have hidden trap doors — roll a 6 to discover one and teleport!",
    "Every 3rd turn, the lights go out — all players move randomly.",
    "Players can plant false evidence once per game to mislead others.",
    "The murder weapon changes every 10 turns — pay attention to the clue clock!",
    "You can bribe another player with clue tokens to see one of their cards.",
    "Secret passages require a password (answer a riddle) to use.",
    "One player is secretly the accomplice and wins if the wrong person is accused.",
    "Evidence degrades — if you don't make an accusation within 15 turns, one clue is removed.",
    "Each room has a special action: Kitchen lets you peek at a card, Library lets you ask a free question.",
  ],
  risk: [
    "Territories produce resources — spend them to upgrade armies to elite forces.",
    "Once per game, you can launch a 'Blitz Attack' — roll 5 dice instead of 3.",
    "Natural disasters hit a random continent every 5 turns, removing armies.",
    "Form a 'Peace Treaty' with one player — lasts 3 turns, then auto-breaks.",
    "Continental bonus armies are doubled but only if you hold the continent for 2 consecutive turns.",
    "Spy units can infiltrate enemy territories — if they go undetected for 2 turns, that territory flips.",
    "Naval units can blockade coastal territories, preventing reinforcements.",
    "Nuclear option: once per game, remove ALL armies from one territory (yours or opponent's).",
    "Mercenary armies can be purchased but might defect on a roll of 1.",
    "Alliance tokens let two players combine armies for a joint attack (split the spoils).",
  ],
  scrabble: [
    "Once per game, you can play a word in any language — but others can challenge it!",
    "Triple word score tiles move to new positions every 5 turns.",
    "You can 'steal' a letter from an opponent's rack by guessing what they have.",
    "Proper nouns are allowed, but only if they're names of people playing the game.",
    "Play a 7-letter word and your opponent must skip their next turn.",
    "Blank tiles are worth 10 points instead of 0, but you must declare the letter immediately.",
    "Every 3rd turn is 'Speed Round' — you have only 30 seconds to play.",
    "You can challenge a word — if it's valid, the challenger loses their turn.",
    "Themed bonus: any word related to the game's theme scores double.",
    "Reverse tiles: play one to make an opponent remove their last word from the board.",
  ],
  "game-of-life": [
    "At any career crossroads, you can gamble double-or-nothing on a coin flip.",
    "Side hustles: spend a turn to start a business that pays passive income.",
    "Random life events: 'Unexpected Inheritance' or 'Identity Theft' cards added to the deck.",
    "Players can trade careers with each other if both agree.",
    "Retirement isn't the end — retired players can mentor active players for shared bonuses.",
    "Midlife crisis: at the halfway point, you can restart your career from scratch with a bonus.",
    "Social media fame: earn bonus money whenever you land on the same space as another player.",
    "Student loans: start with debt, but education spaces pay triple.",
    "Lottery tickets: buy them for $5K, 1-in-6 chance of winning $100K each turn.",
    "Karma track: good deeds earn karma points, redeemable for re-rolls and bonus moves.",
  ],
  "trivial-pursuit": [
    "Steal a wedge: answer a question in another player's strongest category to take their wedge.",
    "Double or nothing: wager a wedge you already have for a harder question.",
    "Lifelines: each player gets 3 lifelines — 50/50, phone-a-friend (ask another player), skip.",
    "Speed round: answer 3 questions in 60 seconds to earn a bonus wedge.",
    "All questions can be about your custom theme instead of standard categories.",
    "Team rounds: every 4th turn, two players team up to answer a super-hard question.",
    "Bluff round: give an answer (right or wrong) — other players bet on whether you're right.",
    "Category auction: bid turn-skips to choose which category you answer.",
    "Revenge card: if you get a question wrong, ask the player who last answered correctly.",
    "Wild card spaces: land here and ANY correct answer from ANY category earns a wedge.",
  ],
  // === CARD GAME MUTATIONS ===
  uno: [
    "Stack Draw 2s and Draw 4s — next player draws the total!",
    "Play a 0 and everyone passes their hand to the left.",
    "Jump-In rule: play an exact match out of turn to steal the turn.",
    "Silent UNO: if you forget to say UNO and someone catches you, draw 4.",
    "Swap hands with anyone when you play a 7.",
    "Challenge a Wild Draw 4 — if it was illegal, the player who played it draws 4 instead.",
    "Mercy rule: if you have 15+ cards, draw until you get a playable card and play it.",
    "Team mode: sit across from your partner and try to go out together.",
  ],
  "exploding-kittens": [
    "Blind draws: you must draw with your eyes closed and can't look at the card for 5 seconds.",
    "Kitten insurance: pay 3 cards to another player to make them draw instead.",
    "Double explode: if two kittens are adjacent in the deck, both go off!",
    "Nope chains: nopes can be noped, but the 3rd nope in a chain causes an explosion.",
    "Steal a defuse from another player by giving them 5 cards of your choice.",
    "Kamikaze: voluntarily explode to eliminate another player of your choice.",
  ],
  "cards-against-humanity": [
    "Haiku round: your answer must form a haiku with the black card.",
    "Gallery round: everyone plays 2 white cards and the judge picks the best combo.",
    "Rando Cardrissian: shuffle a random white card into every round — if it wins 3 times, everyone loses.",
    "Betting round: wager your black cards (points) on whether you'll win this round.",
    "Make it personal: one round per game uses custom cards about the players.",
    "Debate mode: tied answers get 30-second arguments before the judge decides.",
  ],
  "apples-to-apples": [
    "Reverse round: the judge plays a noun, everyone plays adjective cards.",
    "Blind judge: judge picks without knowing who played what (wait, that's normal... double blind!).",
    "Story mode: winning combo must be woven into a running group story.",
    "Challenge: if you think no one has a good match, bet on it — everyone reveals, lowest match draws 2.",
    "Themed rounds: every 3rd round must relate to a specific topic chosen by the judge.",
  ],
  "love-letter": [
    "Poison letter: one card is 'poisoned' — if you're holding it at round end, you lose.",
    "Double agent: once per game, play 2 cards in one turn.",
    "Love triangle: 3-player variant where alliances shift each round.",
    "Anonymous tips: instead of guessing a specific player's card, guess any card in play.",
    "Royal decree: the Princess can now swap with one card in the discard pile.",
  ],
  "sushi-go": [
    "Chef's special: one random card each round is worth triple points.",
    "Food critic: after each round, one player can reject their worst card.",
    "All-you-can-eat: pick 2 cards per turn but pass 2 as well.",
    "Wasabi wild: wasabi multiplies ANY card, not just nigiri.",
    "Takeout: keep one card hidden until end-of-game scoring.",
  ],
  coup: [
    "Deep cover: start with 3 influence cards instead of 2.",
    "Diplomatic immunity: once per game, block any action without revealing.",
    "Double agent: swap one influence secretly when you take income.",
    "Coup insurance: pay 10 coins to survive a coup (keep one influence face-down).",
    "Alliance tokens: two players can share coins for one round.",
  ],
  "the-game": [
    "Freeze: once per game, any player can call 'freeze' and everyone skips their turn.",
    "Wildcard: one card can be placed on any pile regardless of number.",
    "Countdown: you have 30 seconds per turn or auto-fail.",
    "Telepathy bonus: if two players play consecutive numbers, draw 2 fewer cards.",
  ],
  codenames: [
    "Double agent: one card on the board is secretly worth 2 points.",
    "Overtime: if you guess all your words, you can attempt the other team's for bonus points.",
    "Saboteur: one player secretly works for the other team.",
    "Emoji clues: spymaster can only give emoji hints instead of words.",
    "Timed rounds: 60 seconds per clue — no deliberating!",
  ],
  dominion: [
    "Black market: a face-up row of random kingdom cards anyone can buy on their turn.",
    "Taxes: every 5th buy costs 1 extra coin.",
    "Inheritance: pick one kingdom card — all your Estates become copies of it.",
    "Draft start: draft your starting 10 cards instead of the standard copper/estates.",
    "Chaos mode: kingdom cards rotate out every 3 rounds.",
  ],
  werewolf: [
    "Insomnia: one villager wakes up during the night phase and peeks at one card.",
    "Wolfsbane: one player is immune to werewolf attacks for the first night.",
    "Double vote: once per game, a player can cast 2 votes during the day.",
    "Last words: the eliminated player gets to reveal one piece of information.",
    "Timed debate: only 3 minutes of discussion before voting.",
  ],
  skull: [
    "Double dare: bet 2 higher than the current bet to force the previous better to flip first.",
    "Insurance: once per game, survive flipping a skull by discarding 2 of your cards.",
    "Mind games: before flipping, ask one yes/no question to any player.",
    "Skulls wild: if you flip ALL skulls in a round, you win instantly.",
  ],
  "six-nimmt": [
    "Lucky 7: any card with a 7 in it (7, 17, 27...) is worth 0 penalty points.",
    "Bomb: the lowest card played each round gives that player 5 bonus penalty points.",
    "Swap: once per game, swap your played card with another player's before reveal.",
    "Mercy: if you'd take more than 15 points in one round, take only 10.",
  ],
  hanabi: [
    "Genius hint: once per game, give a hint about exact positions instead of colors/numbers.",
    "Oops: if a wrong card is played, one other player can 'save' it by discarding from their hand.",
    "Bonus firework: a 6th color appears — complete it for mega bonus points.",
    "Deadline: you have 20 turns total instead of playing through the deck.",
  ],
  dobble: [
    "Stacking: find 2 matches in a row to score double.",
    "Decoy: shout a wrong match on purpose — if someone else agrees, they lose a point.",
    "Speed demon: fastest match in a round of 5 cards gets 3 points instead of 1.",
    "Memory mode: cards are face-down — flip 2 and find the match from memory.",
  ],
  "phase-10": [
    "Skip a phase: once per game, advance past a phase without completing it.",
    "Steal: complete someone else's current phase requirement to steal their progress.",
    "Wild surge: for one round, all cards act as wilds.",
    "Deadline: if no one completes phase 10 by round 15, highest phase wins.",
  ],
  "skip-bo": [
    "Double play: once per game, play 2 cards from your stockpile in one turn.",
    "Reverse: a special card reverses the build direction (count down instead of up).",
    "Sabotage: once per game, shuffle another player's discard piles.",
    "Speed mode: everyone plays simultaneously — first valid play wins the spot.",
  ],
  "bears-vs-babies": [
    "Mega bear: build a bear with 5+ parts and it eats ALL babies on the table.",
    "Baby boom: double the babies entering play every 3rd round.",
    "Frankenbear: steal one body part from another player's bear.",
    "Pacifist mode: bears with 0 attack parts score bonus points at end of game.",
  ],
  "unstable-unicorns": [
    "Stampede: once per game, move all unicorns from one stable to the discard.",
    "Rainbow shield: protect one unicorn from ALL effects for an entire round.",
    "Unicorn fusion: combine 2 unicorn cards to create a super unicorn worth 3.",
    "Betrayal: once per game, move one of your unicorns to another player's stable as a 'spy'.",
  ],
  "taco-cat": [
    "Reverse slap: slap on a MISMATCH instead of a match for one round.",
    "Penalty pile: wrong slaps add 3 cards to your pile instead of 1.",
    "Speed mode: cards must be flipped within 1 second or auto-penalty.",
    "Double flip: turn over 2 cards at once — match either word to slap.",
  ],
};
