export const BASE_GAMES = [
  {
    id: "monopoly",
    name: "Monopoly",
    description: "Buy, sell, and trade properties to bankrupt your opponents",
    icon: "🏠",
    playerCount: "2-8",
    duration: "60-180 min",
    category: "Strategy",
  },
  {
    id: "clue",
    name: "Clue",
    description: "Solve the mystery — who did it, where, and with what weapon?",
    icon: "🔍",
    playerCount: "3-6",
    duration: "45-60 min",
    category: "Mystery",
  },
  {
    id: "risk",
    name: "Risk",
    description: "Command armies and conquer territories across the globe",
    icon: "⚔️",
    playerCount: "2-6",
    duration: "120-360 min",
    category: "Strategy",
  },
  {
    id: "scrabble",
    name: "Scrabble",
    description: "Form words from letter tiles for maximum points",
    icon: "📝",
    playerCount: "2-4",
    duration: "60-90 min",
    category: "Word",
  },
  {
    id: "game-of-life",
    name: "Game of Life",
    description: "Navigate life's milestones from college to retirement",
    icon: "🎡",
    playerCount: "2-6",
    duration: "60-90 min",
    category: "Family",
  },
  {
    id: "trivial-pursuit",
    name: "Trivial Pursuit",
    description: "Test your knowledge across six categories",
    icon: "🧠",
    playerCount: "2-6",
    duration: "60-120 min",
    category: "Trivia",
  },
] as const;

export type BaseGameId = (typeof BASE_GAMES)[number]["id"];

export const RULE_MUTATIONS: Record<string, string[]> = {
  monopoly: [
    "Free Parking collects all tax money — whoever lands there gets the pot!",
    "If you roll doubles three times, you go to jail AND lose a property of your choice.",
    "Every time someone passes Go, ALL players collect $100.",
    "You can challenge another player to a trivia question to avoid paying rent.",
    "Properties can only be bought at auction — no direct purchases allowed.",
    "Landing on someone's hotel triggers a 'Buyout Battle' — both players roll, highest wins the property.",
    "Every 5th turn is 'Wild Card' turn — draw from a custom event deck.",
    "Players can form temporary alliances that last exactly 3 rounds.",
    "Jail becomes 'Vacation' — you collect double salary but skip 2 turns.",
    "If you go bankrupt, you become a 'Ghost Player' who can still collect Go money and mess with others.",
  ],
  clue: [
    "Each player has a secret 'alibi' card that can be played once to deflect suspicion.",
    "Rooms have hidden trap doors — roll a 6 to discover one and teleport!",
    "Every 3rd turn, the lights go out — all players move randomly.",
    "Players can plant false evidence once per game to mislead others.",
    "The murder weapon changes every 10 turns — pay attention to the clue clock!",
    "You can bribe another player with clue tokens to see one of their cards.",
    "Secret passages require a password (answer a riddle) to use.",
    "One player is secretly the accomplice and wins if the wrong person is accused.",
    "Evidence degrades — if you don't make an accusation within 15 turns, one clue is removed.",
    "Each room has a special action: Kitchen lets you peek at a card, Library lets you ask a free question.",
  ],
  risk: [
    "Territories produce resources — spend them to upgrade armies to elite forces.",
    "Once per game, you can launch a 'Blitz Attack' — roll 5 dice instead of 3.",
    "Natural disasters hit a random continent every 5 turns, removing armies.",
    "Form a 'Peace Treaty' with one player — lasts 3 turns, then auto-breaks.",
    "Continental bonus armies are doubled but only if you hold the continent for 2 consecutive turns.",
    "Spy units can infiltrate enemy territories — if they go undetected for 2 turns, that territory flips.",
    "Naval units can blockade coastal territories, preventing reinforcements.",
    "Nuclear option: once per game, remove ALL armies from one territory (yours or opponent's).",
    "Mercenary armies can be purchased but might defect on a roll of 1.",
    "Alliance tokens let two players combine armies for a joint attack (split the spoils).",
  ],
  scrabble: [
    "Once per game, you can play a word in any language — but others can challenge it!",
    "Triple word score tiles move to new positions every 5 turns.",
    "You can 'steal' a letter from an opponent's rack by guessing what they have.",
    "Proper nouns are allowed, but only if they're names of people playing the game.",
    "Play a 7-letter word and your opponent must skip their next turn.",
    "Blank tiles are worth 10 points instead of 0, but you must declare the letter immediately.",
    "Every 3rd turn is 'Speed Round' — you have only 30 seconds to play.",
    "You can challenge a word — if it's valid, the challenger loses their turn.",
    "Themed bonus: any word related to the game's theme scores double.",
    "Reverse tiles: play one to make an opponent remove their last word from the board.",
  ],
  "game-of-life": [
    "At any career crossroads, you can gamble double-or-nothing on a coin flip.",
    "Side hustles: spend a turn to start a business that pays passive income.",
    "Random life events: 'Unexpected Inheritance' or 'Identity Theft' cards added to the deck.",
    "Players can trade careers with each other if both agree.",
    "Retirement isn't the end — retired players can mentor active players for shared bonuses.",
    "Midlife crisis: at the halfway point, you can restart your career from scratch with a bonus.",
    "Social media fame: earn bonus money whenever you land on the same space as another player.",
    "Student loans: start with debt, but education spaces pay triple.",
    "Lottery tickets: buy them for $5K, 1-in-6 chance of winning $100K each turn.",
    "Karma track: good deeds earn karma points, redeemable for re-rolls and bonus moves.",
  ],
  "trivial-pursuit": [
    "Steal a wedge: answer a question in another player's strongest category to take their wedge.",
    "Double or nothing: wager a wedge you already have for a harder question.",
    "Lifelines: each player gets 3 lifelines — 50/50, phone-a-friend (ask another player), skip.",
    "Speed round: answer 3 questions in 60 seconds to earn a bonus wedge.",
    "All questions can be about your custom theme instead of standard categories.",
    "Team rounds: every 4th turn, two players team up to answer a super-hard question.",
    "Bluff round: give an answer (right or wrong) — other players bet on whether you're right.",
    "Category auction: bid turn-skips to choose which category you answer.",
    "Revenge card: if you get a question wrong, ask the player who last answered correctly.",
    "Wild card spaces: land here and ANY correct answer from ANY category earns a wedge.",
  ],
};
